# -*- mode: ruby -*-
# vi: set ft=ruby :

machines=[
  {
    :hostname => "k8s-master",
    :ip => "192.168.56.10",
    :box => "ubuntu/jammy64",
    :ram => 2048,
    :cpu => 2
  },
  {
    :hostname => "k8s-worker1",
    :ip => "192.168.56.11",
    :box => "ubuntu/jammy64",
    :ram => 1024,
    :cpu => 1
  },
  {
    :hostname => "k8s-worker2",
    :ip => "192.168.56.12",
    :box => "ubuntu/jammy64",
    :ram => 1024,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
  config.ssh.insert_key = true
  config.ssh.forward_agent = false  
  machines.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.memory = machine[:ram]
              vb.cpus = machine[:cpu]

          end
      end
  end
end
