# generated by datamodel-codegen:
#   filename:  conversation/conversation.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel

from ..common import timestamp_schema, uuid_schema


class Model(BaseModel):
    id: uuid_schema.Model
    match_id: uuid_schema.Model
    created_at: timestamp_schema.Model
