# generated by datamodel-codegen:
#   filename:  conversation/message.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel, constr

from ..common import timestamp_schema, uuid_schema


class Message(BaseModel):
    id: uuid_schema.Uuid
    conversation_id: uuid_schema.Uuid
    sender_id: uuid_schema.Uuid
    content: constr(max_length=2000)
    sent_at: timestamp_schema.Timestamp
