# generated by datamodel-codegen:
#   filename:  common/pagination.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel, conint


class Model(BaseModel):
    limit: conint(ge=1, le=100) | None = None
    offset: conint(ge=0) | None = None
