# generated by datamodel-codegen:
#   filename:  common/timestamp.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import AwareDatetime, RootModel


class Model(RootModel[AwareDatetime]):
    root: AwareDatetime
