# generated by datamodel-codegen:
#   filename:  common/uuid.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import RootModel


class Uuid(RootModel[UUID]):
    root: UUID
