# generated by datamodel-codegen:
#   filename:  profile/profile.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from datetime import date

from pydantic import AnyUrl, BaseModel, constr

from ..common import uuid_schema


class Model(BaseModel):
    user_id: uuid_schema.Model
    display_name: constr(min_length=1)
    bio: constr(max_length=500) | None = None
    birth_date: date | None = None
    photos: list[AnyUrl] | None = None
