# generated by datamodel-codegen:
#   filename:  profile/profile_preferences.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint


class GenderPreference(Enum):
    male = 'male'
    female = 'female'
    non_binary = 'non_binary'
    other = 'other'


class Model(BaseModel):
    age_min: conint(ge=18) | None = None
    age_max: conint(le=99) | None = None
    distance_km: conint(ge=1) | None = None
    gender_preferences: list[GenderPreference] | None = None
