# generated by datamodel-codegen:
#   filename:  api/error.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    code: str
    message: str
