# generated by datamodel-codegen:
#   filename:  api/response.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from . import error_schema


class Model(BaseModel):
    data: Any | None = None
    error: error_schema.Model | None = None
