"""fix user/profile tables and add a test

Revision ID: 3e6c97507604
Revises: a98fab32c00d
Create Date: 2026-01-28 09:13:04.868868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e6c97507604'
down_revision: Union[str, Sequence[str], None] = 'a98fab32c00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('profile_id'), table_name='profile_preferences')
    op.drop_constraint(op.f('profile_preferences_ibfk_1'), 'profile_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'profile_preferences', 'profiles', ['profile_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('profile_preferences', 'id')
    op.add_column('profiles', sa.Column('birth_date', sa.Date(), nullable=True))
    #op.drop_index(op.f('user_id'), table_name='profiles')
    op.drop_column('profiles', 'id')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.add_column('profiles', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    #op.create_index(op.f('user_id'), 'profiles', ['user_id'], unique=True)
    op.drop_column('profiles', 'birth_date')
    op.add_column('profile_preferences', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    op.drop_constraint(None, 'profile_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('profile_preferences_ibfk_1'), 'profile_preferences', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    #op.create_index(op.f('profile_id'), 'profile_preferences', ['profile_id'], unique=True)
    # ### end Alembic commands ###
