"""update tables and add a test

Revision ID: c6ab282c4594
Revises: 3e6c97507604
Create Date: 2026-01-28 16:21:00.253346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6ab282c4594'
down_revision: Union[str, Sequence[str], None] = '3e6c97507604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('matches_ibfk_1'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_ibfk_2'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'users', ['user_a_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matches', 'users', ['user_b_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_ibfk_2'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.alter_column('profile_preferences', 'min_age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('profile_preferences', 'max_age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('profile_preferences', 'distance_km',
               existing_type=mysql.INTEGER(),
               nullable=False)
    #op.drop_index(op.f('profile_id'), table_name='profile_preferences')
    op.alter_column('profiles', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    #op.drop_index(op.f('user_id'), table_name='profiles')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    #op.create_index(op.f('user_id'), 'profiles', ['user_id'], unique=True)
    op.alter_column('profiles', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    #op.create_index(op.f('profile_id'), 'profile_preferences', ['profile_id'], unique=True)
    op.alter_column('profile_preferences', 'distance_km',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('profile_preferences', 'max_age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('profile_preferences', 'min_age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_ibfk_2'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_ibfk_2'), 'matches', 'users', ['user_b_id'], ['id'])
    op.create_foreign_key(op.f('matches_ibfk_1'), 'matches', 'users', ['user_a_id'], ['id'])
    # ### end Alembic commands ###
