# generated by datamodel-codegen:
#   filename:  user/user.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr


class UserCreate(BaseModel):
    """
    Schema for creating a new user.
    UUID is auto-generated. Is_active defaults to True. 
    Will change if do not answer to match selection. 
    """
    email: EmailStr
    username: str
    password: str
    

class UserRead(BaseModel):
    """
    Schema for reading user information.
    All information except password is included.
    """
    id: UUID
    email: EmailStr
    username: str
    is_active: bool | None = True
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)