# generated by datamodel-codegen:
#   filename:  user/user_settings.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel


class UserSettings(BaseModel):
    language: str | None = 'fr'
    email_notifications: bool | None = True
    weekly_pool_enabled: bool | None = True
