# generated by datamodel-codegen:
#   filename:  user/user.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr


class UserCreate(BaseModel):
    email: EmailStr
    username: str
    password: str
    

class UserRead(BaseModel):
    id: UUID
    email: EmailStr
    username: str
    is_active: bool | None = True
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)