# generated by datamodel-codegen:
#   filename:  user/user.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel, EmailStr

from ..common import timestamp_schema, uuid_schema


class Model(BaseModel):
    id: uuid_schema.Model
    email: EmailStr
    is_active: bool | None = True
    created_at: timestamp_schema.Model
