# generated by datamodel-codegen:
#   filename:  matching/active_match.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from ..common import timestamp_schema, uuid_schema


class Model(BaseModel):
    id: uuid_schema.Model
    users: list[uuid_schema.Model] = Field(..., max_length=2, min_length=2)
    started_at: timestamp_schema.Model
