# generated by datamodel-codegen:
#   filename:  matching/active_match.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import Field

from .match_schema import MatchRead


class ActiveMatchRead(MatchRead):
    id: UUID
    users: list[UUID] = Field(..., max_length=2, min_length=2)
    started_at: datetime
