# generated by datamodel-codegen:
#   filename:  matching/match.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel


class Status(Enum):
    accepted = 'accepted'
    rejected = 'rejected'
    expired = 'expired'

class MatchRead(BaseModel):
    """
    Schema for reading match information.
    allows to get the status of a match for a specific profile.
    """
    match_id: UUID
    profile_id: UUID
    status: Status

class MatchUpdate(BaseModel):
    """
    Schema for updating match information.
    allows to update the status of a match for a specific profile.
    """
    match_id: UUID
    status: Status

