# generated by datamodel-codegen:
#   filename:  matching/match_decision.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ..common.uuid_schema import Uuid


class Decision(Enum):
    continue_ = "continue"
    requeue = "requeue"
    block = "block"

class MatchDecision(BaseModel):
    match_id: Uuid
    decision: Decision