# generated by datamodel-codegen:
#   filename:  matching/match.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ..common import uuid_schema


class Status(Enum):
    pending = 'pending'
    accepted = 'accepted'
    rejected = 'rejected'
    expired = 'expired'


class Match(BaseModel):
    match_id: uuid_schema.Model
    profile_id: uuid_schema.Model
    status: Status
