# generated by datamodel-codegen:
#   filename:  matching/past_match.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from enum import Enum

from pydantic import Field

from ..common import timestamp_schema, uuid_schema
from .match_schema import Match


class Outcome(Enum):
    mutual_stop = 'mutual_stop'
    blocked = 'blocked'
    expired = 'expired'

class PastMatch(Match):
    id: uuid_schema.Uuid
    users: list[uuid_schema.Uuid] = Field(..., max_length=2, min_length=2)
    ended_at: timestamp_schema.Timestamp
    outcome: Outcome
