# generated by datamodel-codegen:
#   filename:  matching/weekly_pool.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr

from ..common import uuid_schema
from . import match_schema


class WeeklyPool(BaseModel):
    user_id: uuid_schema.Model
    week: constr(pattern=r'^\d{4}-W\d{2}$')
    matches: list[match_schema.Model] = Field(..., max_length=10, min_length=1)
