# generated by datamodel-codegen:
#   filename:  matching/weekly_pool.schema.json
#   timestamp: 2026-01-27T08:57:01+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field, constr

from . import match_schema


class WeeklyPoolRead(BaseModel):
    user_id: UUID
    week: constr(pattern=r'^\d{4}-W\d{2}$')
    matches: list[match_schema.MatchRead] = Field(..., max_length=10, min_length=1)

class WeeklyPoolUpdate(BaseModel):
    user_id: UUID
    week: constr(pattern=r'^\d{4}-W\d{2}$')
    matches: list[match_schema.MatchRead] = Field(..., max_length=10, min_length=1)
